# Generated by Django 5.0.2 on 2024-03-04 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogpost_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='photo',
            field=models.ImageField(null=True, upload_to='static/blog/images'),
        ),
    ]
